const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/json",
    },
  });
}

function escapeHtml(value: unknown) {
  return String(value ?? "").replace(/[&<>"']/g, (char) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    "\"": "&quot;",
    "'": "&#39;",
  }[char] || char));
}

function isEmail(value: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

function normalizeRecipients(value: unknown) {
  const raw = Array.isArray(value) ? value : [value];
  return [...new Set(raw.map((email) => String(email || "").trim().toLowerCase()).filter(isEmail))];
}

function cleanPdfText(value: unknown) {
  return String(value ?? "")
    .replace(/[^\x20-\x7E]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function escapePdfText(value: unknown) {
  return cleanPdfText(value).replace(/[\\()]/g, "\\$&");
}

function wrapPdfText(value: unknown, maxLength = 72) {
  const words = cleanPdfText(value).split(" ").filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if (!line) {
      line = word;
    } else if ((line.length + word.length + 1) <= maxLength) {
      line += ` ${word}`;
    } else {
      lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  return lines.length ? lines : ["-"];
}

function bytesToBase64(bytes: Uint8Array) {
  let binary = "";
  const chunkSize = 0x8000;
  for (let i = 0; i < bytes.length; i += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunkSize));
  }
  return btoa(binary);
}

function buildRegistrationPdf(details: {
  schoolName: string;
  studentName: string;
  rows: string[][];
}) {
  const commands: string[] = [
    "BT",
    "/F1 10 Tf",
    "50 790 Td",
    "0.10 0.28 0.55 rg",
    `/F2 20 Tf (${escapePdfText(details.schoolName)}) Tj`,
    "0 -26 Td",
    "0.05 0.08 0.12 rg",
    `/F2 15 Tf (Student Registration Form) Tj`,
    "0 -18 Td",
    `/F1 10 Tf (Generated by Schoolix) Tj`,
    "0 -26 Td",
    "0.20 0.24 0.31 rg",
    `/F2 12 Tf (Student: ${escapePdfText(details.studentName || "Student")}) Tj`,
    "0 -22 Td",
  ];

  for (const [label, value] of details.rows) {
    const lines = wrapPdfText(value, 64);
    commands.push("0.39 0.45 0.55 rg", `/F2 9 Tf (${escapePdfText(label)}) Tj`);
    commands.push("110 0 Td", "0.05 0.08 0.12 rg", `/F1 10 Tf (${escapePdfText(lines[0])}) Tj`);
    for (const extraLine of lines.slice(1, 3)) {
      commands.push("0 -13 Td", `/F1 10 Tf (${escapePdfText(extraLine)}) Tj`);
    }
    commands.push("-110 -18 Td");
  }
  commands.push("0 -8 Td", "0.39 0.45 0.55 rg", "/F1 8 Tf (Please keep the login password private. Contact the school office for corrections.) Tj", "ET");

  const stream = commands.join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
  ];
  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
  return bytesToBase64(new TextEncoder().encode(pdf));
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", {
      status: 200,
      headers: corsHeaders,
    });
  }

  try {
    if (req.method !== "POST") {
      return jsonResponse({ error: "Method not allowed" }, 405);
    }

    const brevoApiKey = Deno.env.get("BREVO_API_KEY");
    if (!brevoApiKey) {
      return jsonResponse({ error: "BREVO_API_KEY is not configured" }, 500);
    }

    let payload;
    try {
      payload = await req.json();
    } catch {
      return jsonResponse({ error: "Invalid JSON request body" }, 400);
    }

    const recipients = normalizeRecipients(payload.recipients || payload.email || payload.parentEmail);
    if (!recipients.length) {
      return jsonResponse({ error: "At least one valid recipient email is required" }, 400);
    }

    const schoolName = String(payload.schoolName || "Schoolix").trim();
    const studentName = String(payload.studentName || "Student").trim();
    const studentId = String(payload.studentId || "").trim();
    const srNumber = String(payload.srNumber || "").trim();
    const className = String(payload.className || "").trim();
    const section = String(payload.section || "").trim();
    const roll = String(payload.roll || "").trim();
    const gender = String(payload.gender || "").trim();
    const category = String(payload.category || "").trim();
    const bloodGroup = String(payload.bloodGroup || "").trim();
    const religion = String(payload.religion || "").trim();
    const previousSchool = String(payload.previousSchool || "").trim();
    const aadharNumber = String(payload.aadharNumber || "").trim();
    const dob = String(payload.dob || "").trim();
    const father = String(payload.father || "").trim();
    const fatherPhone = String(payload.fatherPhone || "").trim();
    const mother = String(payload.mother || "").trim();
    const motherPhone = String(payload.motherPhone || "").trim();
    const phone = String(payload.phone || "").trim();
    const dateOfAdmission = String(payload.dateOfAdmission || "").trim();
    const yearOfAdmission = String(payload.yearOfAdmission || "").trim();
    const academicSession = String(payload.academicSession || "").trim();
    const loginEmail = String(payload.loginEmail || recipients[0]).trim();
    const parentEmail = String(payload.parentEmail || "").trim();
    const address = String(payload.address || "").trim();
    const documentList = String(payload.documentList || "").trim();
    const status = String(payload.status || "").trim();
    const feeAmount = String(payload.feeAmount || "").trim();
    const feeMonth = String(payload.feeMonth || "").trim();
    const appLink = String(payload.appLink || Deno.env.get("SCHOOLIX_APP_LINK") || "https://schoolix-48107.web.app/dist/Schoolix.apk").trim();
    const temporaryPassword = String(payload.temporaryPassword || "").trim();
    const classLabel = [className, section].filter(Boolean).join("-");
    const subject = `${schoolName} registration confirmed - ${studentName}`;

    const rows = [
      ["Student Name", studentName],
      ["Student ID", studentId],
      ["SR Number", srNumber],
      ["Class", classLabel],
      ["Roll Number", roll],
      ["Status", status],
      ["Gender", gender],
      ["Category", category],
      ["Blood Group", bloodGroup],
      ["Religion", religion],
      ["Previous School", previousSchool],
      ["Aadhaar Number", aadharNumber],
      ["Date of Birth", dob],
      ["Father", father],
      ["Father Phone", fatherPhone],
      ["Mother", mother],
      ["Mother Phone", motherPhone],
      ["Phone", phone],
      ["Date of Admission", dateOfAdmission],
      ["Year of Admission", yearOfAdmission],
      ["Academic Session", academicSession],
      ["Parent Email", parentEmail],
      ["Address", address],
      ["Submitted Documents", documentList],
      ["Imposed Fee", feeAmount ? `${feeAmount}${feeMonth ? ` for ${feeMonth}` : ""}` : ""],
      ["Login Email", loginEmail],
      ["Temporary Password", temporaryPassword],
    ].filter(([, value]) => value);

    const pdfRows = rows.filter(([label]) => label !== "Temporary Password");
    const registrationPdf = buildRegistrationPdf({
      schoolName,
      studentName,
      rows: pdfRows,
    });

    const textContent = `Dear Parent/Student,

Greetings from ${schoolName}.

${studentName}'s registration has been completed successfully. The attached PDF contains the registration form details.

Login Email: ${loginEmail}
Temporary Password: ${temporaryPassword || "Contact school office"}
Student ID: ${studentId || "-"}
Class: ${classLabel || "-"}

Download the Schoolix Android app:
${appLink}

Please sign in to the student panel with the same password shown above and change it after first login. Keep these credentials private.

Regards,
${schoolName}`;

    const htmlRows = rows.map(([label, value]) => `
      <tr>
        <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;color:#64748b;font-weight:700;">${escapeHtml(label)}</td>
        <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;color:#111827;font-weight:700;">${escapeHtml(value)}</td>
      </tr>
    `).join("");

    const htmlContent = `
      <div style="font-family:Arial,Helvetica,sans-serif;background:#eef4fb;padding:28px;color:#0f172a;line-height:1.6;">
        <div style="max-width:680px;margin:0 auto;background:#ffffff;border:1px solid #dbe4f0;border-radius:18px;overflow:hidden;box-shadow:0 16px 44px rgba(15,23,42,0.10);">
          <div style="background:#123f7a;color:#ffffff;padding:26px 28px;">
            <div style="font-size:12px;text-transform:uppercase;letter-spacing:.12em;opacity:.86;font-weight:800;">${escapeHtml(schoolName)}</div>
            <h1 style="margin:8px 0 6px;font-size:25px;line-height:1.2;">Registration Confirmed</h1>
            <div style="font-size:14px;opacity:.9;">${escapeHtml(studentName)} has been added to the Schoolix student panel.</div>
          </div>
          <div style="padding:26px 28px;">
            <p style="margin:0 0 14px;">Dear Parent/Student,</p>
            <p style="margin:0 0 18px;">The registration has been completed successfully. A polished PDF copy of the registration form is attached with this email.</p>
            <div style="background:#f8fafc;border:1px solid #dbe4f0;border-radius:14px;padding:16px 18px;margin:18px 0;">
              <div style="font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:#64748b;font-weight:800;margin-bottom:10px;">Student Panel Login</div>
              <div style="font-size:14px;margin-bottom:8px;"><strong>Email:</strong> ${escapeHtml(loginEmail)}</div>
              <div style="font-size:14px;margin-bottom:8px;"><strong>Password:</strong> <span style="font-family:Consolas,Monaco,monospace;background:#e8f1ff;color:#123f7a;border-radius:8px;padding:5px 9px;font-weight:800;">${escapeHtml(temporaryPassword || "Contact school office")}</span></div>
              <div style="font-size:13px;color:#475569;">You can use this same password to sign in to the student panel. Please change it after first login.</div>
            </div>
            <table style="width:100%;border-collapse:separate;border-spacing:0;margin:18px 0;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
              <tbody>${htmlRows}</tbody>
            </table>
            <p style="margin:22px 0;">
              <a href="${escapeHtml(appLink)}" style="display:inline-block;background:#0f766e;color:#ffffff;text-decoration:none;padding:12px 18px;border-radius:10px;font-weight:800;">Download Schoolix APK</a>
            </p>
            <p style="color:#475569;font-size:13px;margin:0;">Please keep these credentials private. For any correction in the registration details, contact the school office.</p>
            <p style="margin:24px 0 0;">Regards,<br><strong>${escapeHtml(schoolName)}</strong></p>
          </div>
        </div>
      </div>
    `;

    const brevoResponse = await fetch("https://api.brevo.com/v3/smtp/email", {
      method: "POST",
      headers: {
        "api-key": brevoApiKey,
        "Content-Type": "application/json",
        "Accept": "application/json",
      },
      body: JSON.stringify({
        sender: {
          name: "Schoolix Registration",
          email: "schoolixteam@gmail.com",
        },
        to: recipients.map((email) => ({ email })),
        subject,
        textContent,
        htmlContent,
        attachment: [{
          name: `${studentId || "student"}-registration-form.pdf`,
          content: registrationPdf,
        }],
      }),
    });

    const brevoData = await brevoResponse.text();
    if (!brevoResponse.ok) {
      console.error("Brevo Error:", brevoData);
      return jsonResponse({
        error: "Failed to send registration email",
        details: brevoData,
      }, 500);
    }

    return jsonResponse({
      success: true,
      message: "Registration email sent successfully",
      recipients,
    });
  } catch (error) {
    console.error("Function Error:", error);
    return jsonResponse({
      error: error instanceof Error ? error.message : "Internal server error",
    }, 500);
  }
});
